// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";

function str(prim) {
  return prim;
}

function App$Button(Props) {
  var onClick = Props.onClick;
  var label = Props.label;
  return React.createElement("button", {
              onClick: onClick
            }, label);
}

var Button = {
  make: App$Button
};

function App(Props) {
  var match = React.useState(function () {
        return 0;
      });
  var setState = match[1];
  var state = match[0];
  var handleIncrement = function (_event) {
    return Curry._1(setState, (function (param) {
                  return state + 1 | 0;
                }));
  };
  return React.createElement(React.Fragment, undefined, React.createElement("h1", undefined, state), React.createElement(App$Button, {
                  onClick: handleIncrement,
                  label: "Increment"
                }));
}

var make = App;

export {
  str ,
  Button ,
  make ,
  
}
/* react Not a pure module */
