// Generated by ReScript, PLEASE EDIT WITH CARE


var name = "Carol";

var lastname = "Name: " + name;

var names = [
  "Carol",
  "Carolis"
];

var personObject = {
  name: "Carolis",
  age: 22
};

function sum(a, b) {
  return a + b | 0;
}

function namedSum(a, b) {
  return a + b | 0;
}

function sumCurry(param) {
  return 1 + param | 0;
}

var name$1 = "Carol";

var message = name$1 === "Carol" ? "Hi Carol" : "Hi " + name$1;

var age = 1;

var price = 100.25;

var letter = /* "C" */67;

var isAdmin = false;

var names2 = {
  hd: "Carol",
  tl: {
    hd: "Carolis",
    tl: /* [] */0
  }
};

var namesTuple = [
  "Carol",
  22
];

var person = {
  name: "Carol",
  age: 22
};

export {
  age ,
  price ,
  name ,
  lastname ,
  letter ,
  isAdmin ,
  names ,
  names2 ,
  namesTuple ,
  person ,
  personObject ,
  sum ,
  namedSum ,
  sumCurry ,
  message ,
  
}
/* message Not a pure module */
