// Generated by ReScript, PLEASE EDIT WITH CARE


var names = [
  "Carol",
  "Carolis"
];

var personObject = {
  name: "Carolis"
};

function sum(a, b) {
  return a + b | 0;
}

function namedSum(a, b) {
  return a + b | 0;
}

var age = 1;

var price = 100.25;

var name = "Carol";

var lastname = "Name: $name";

var letter = /* "C" */67;

var isAdmin = false;

var names2 = {
  hd: "Carol",
  tl: {
    hd: "Carolis",
    tl: /* [] */0
  }
};

var namesTuple = [
  "Carol",
  22
];

var person = {
  name: "Carol"
};

export {
  age ,
  price ,
  name ,
  lastname ,
  letter ,
  isAdmin ,
  names ,
  names2 ,
  namesTuple ,
  person ,
  personObject ,
  sum ,
  namedSum ,
  
}
/* No side effect */
